### ISSUE TITLE
Cant locate the BDSKY model using BEAST2.7

### ISSUE THREAD

**Issue by george-githinji** [CompEvol/CBAN#102]
This could be a naive question, but would like to know how to call or install the BDSKY package in BEAST 2.7.0

**Comment by rbouckaert** [comment]
@george-githinji  the BDSKY package and quite a few other packages have not been migrated to v2.7 yet. 

You can run v2.6 and v2.7 next to each other -- they use different package directories -- so if you need packages that have not been migrated yet you should use v2.6.
