### ISSUE TITLE
Is it really necessary to have a new packages.xml for each release?

### ISSUE THREAD

**Issue by tgvaughan** [CompEvol/CBAN#2]
Surely the version.xml (and its analogue in the packages.xml file) contains enough information in order to deduce whether the package is suitable for the installed version of BEAST.

The problem with having a huge number of package.XMLs for the central repository is that every time a package developer releases a new version they have to update each of these with the same information or risk having some users become ignorant of new versions of the package.

**Comment by rbouckaert** [comment]
I am aware of the problem -- it used to be possible that package X.1 relies on BEAST version Y.1 but does not work with version Y.2, but package X.2 did (but did not work with Y.1). This is probably not relevant any more, so we may get away with having one package XML per major BEAST release from here onward.

**Comment by tgvaughan** [comment]
In the instance that a new version of a package is available but is incompatible with the installed BEAST, maybe we could colour its entry in the package manager red?  Similarly for packages that depend on other packages that can't be installed for this reason.

**Comment by tgvaughan** [comment]
Why can't we package up beast itself as an "add-on" and give it an entry in packages.xml?  Then we can automatically upgrade.

**Comment by rbouckaert** [comment]
Sounds like a great idea -- would be good if v2.4.0 will be the last release, consisting of a addonmanager only. We can also easily split off BEAUti in its own package, since that is where most of the problems stem from.

**Comment by rbouckaert** [comment]
closed by BEAST release v2.4.0
