### ISSUE TITLE
packages.xml not well-formed

### ISSUE THREAD

**Issue by xrotwang** [CompEvol/CBAN#3]
Due to a stray `<` in line 129, [packages.xml](https://raw.githubusercontent.com/CompEvol/CBAN/master/packages.xml) is currently not well-formed, which makes the package management via `beauti` unusable. Maybe a command line option for `beauti` which allows using a local (and possibly repaired) version of `packages.xml` would be a good solution for problems of this kind.

**Comment by rbouckaert** [comment]
Thanks Denise!

Closed by 15dc7e953888735ecd323c0634cbe52adf0f63b8
